Version: '${project.version}'

Config:
  Command: "leaderboard"

Embed:
    Title: "ðŸ† ``{BOARD}`` Leaderboard ({TIME}) ðŸ†"
    Footer:
      Text: "{AUTHOR}"

Leaderboard:
  Format: "{NAME} -> {VALUE} {BOARD}"
  Top: 10